version: 2

defaults: &defaults
  environment:
    CGO_ENABLED: 0
  working_directory: /opt/merlin

golang: &golang
  <<: *defaults
  docker:
    - image: golang:1.12
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json

gcloud: &gcloud
  <<: *defaults
  docker:
    - image: gcr.io/cloud-builders/gcloud
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json

jobs:
  modules:
    <<: *golang
    steps:
      - checkout
      - run:
          name: Re-set global url with auth
          command: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - run:
          name: Make lock copy
          command: cp go.sum go.sum.fix
      - restore_cache:
          keys:
            - vendor-{{ checksum "go.sum.fix" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -e vendor ]; then
              go mod vendor
            fi
      - save_cache:
          key: vendor-{{ checksum "go.sum.fix" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths: '*'

  build:
    <<: *golang
    steps:
      - attach_workspace:
          at: /opt/merlin
      - run:
          name: Check compilation
          command: make docker-build

  push-image:
    <<: *gcloud
    steps:
      - attach_workspace:
          at: /opt/merlin
      - run:
          name: Submit build task to container builder
          command: |
            # Authorize
            echo "${MERCARI_ARTIFACT_CONTAINER_BUILDER_CREDENTIALS_JSON}" > ${GOOGLE_APPLICATION_CREDENTIALS}
            gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}
            # Delete symlink files
            find vendor -type l -delete

            # Build version
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                export VERSION=$(date +%Y%m%d)-${CIRCLE_BUILD_NUM}
                export SUBSTITUTIONS="_BUILD_TARGET=master,_BUILD_VERSION=$VERSION,_BUILD_NUMBER=$CIRCLE_BUILD_NUM"
            else
                echo "Change was not pushed to master branch, will not build image for it"
                exit 1
            fi

            echo "submittigng cloud build with SUBSTITUTIONS=$SUBSTITUTIONS"
            # Build the image
            gcloud builds submit . \
              --project=mercari-us-double \
              --config="cloudbuild.yaml" \
              --gcs-log-dir="gs://mercari-us-double-cloudbuild-logs/logs" \
              --substitutions="$SUBSTITUTIONS"

workflows:
  version: 2
  build-and-test:
    jobs:
      - modules:
          context: org-global
      - build:
          requires:
            - modules
      - push-image:
          context: org-global
          requires:
            - build
