# permissions to do edit clusterrulenamespacerequiredlabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrulenamespacerequiredlabel-editor-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulenamespacerequiredlabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulenamespacerequiredlabels/status
  verbs:
  - get
  - patch
  - update
