# permissions to do viewer clusterruleconfigmapunuseds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterruleconfigmapunused-viewer-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterruleconfigmapunuseds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterruleconfigmapunuseds/status
  verbs:
  - get
