# permissions to do edit clusterrulehpareplicapercentages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrulehpareplicapercentage-editor-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulehpareplicapercentages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulehpareplicapercentages/status
  verbs:
  - get
  - patch
  - update
