# permissions to do viewer clusterrulesecretunuseds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrulesecretunused-viewer-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulesecretunuseds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulesecretunuseds/status
  verbs:
  - get
