# permissions to do viewer clusterrulepdbinvalidselectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrulepdbinvalidselector-viewer-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulepdbinvalidselectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulepdbinvalidselectors/status
  verbs:
  - get
