# permissions to do edit clusterruleserviceinvalidselector.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterruleserviceinvalidselector-editor-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterruleserviceinvalidselector
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterruleserviceinvalidselector/status
  verbs:
  - get
  - patch
  - update
