# permissions to do viewer clusterruleserviceinvalidselector.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterruleserviceinvalidselector-viewer-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterruleserviceinvalidselector
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterruleserviceinvalidselector/status
  verbs:
  - get
