# permissions to do viewer clusterrulenamespacerequiredlabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrulenamespacerequiredlabel-viewer-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulenamespacerequiredlabels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulenamespacerequiredlabels/status
  verbs:
  - get
