# permissions to do edit clusterrulesecretunuseds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrulesecretunused-editor-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulesecretunuseds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulesecretunuseds/status
  verbs:
  - get
  - patch
  - update
