# permissions to do edit clusterrulepdbinvalidselectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrulepdbinvalidselector-editor-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulepdbinvalidselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulepdbinvalidselectors/status
  verbs:
  - get
  - patch
  - update
