# permissions to do edit deploymentevaluators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentevaluator-editor-role
rules:
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - deploymentevaluators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - deploymentevaluators/status
  verbs:
  - get
  - patch
  - update
