# permissions to do edit namespaceevaluators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceevaluator-editor-role
rules:
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - namespaceevaluators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - namespaceevaluators/status
  verbs:
  - get
  - patch
  - update
