# permissions to do edit notifier.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notifier-editor-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - notifier
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - notifier/status
  verbs:
  - get
  - patch
  - update
