# permissions to do viewer notifier.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notifier-viewer-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - notifier
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - notifier/status
  verbs:
  - get
