# permissions to do viewer notifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notifiers-viewer-role
rules:
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - notifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - notifiers/status
  verbs:
  - get
