# permissions to do edit notifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notifiers-editor-role
rules:
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - notifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - notifiers/status
  verbs:
  - get
  - patch
  - update
