# permissions to do edit podevaluators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podevaluator-editor-role
rules:
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - podevaluators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - podevaluators/status
  verbs:
  - get
  - patch
  - update
