# permissions to do viewer podevaluators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podevaluator-viewer-role
rules:
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - podevaluators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - watcher.merlin.mercari.com
  resources:
  - podevaluators/status
  verbs:
  - get
