
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - clusterrulenamespacerequiredlabel
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - clusterrulepdbinvalidselector
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - clusterrulepdbminalloweddisruption
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - clusterruleserviceinvalidselector
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - rulepdbminalloweddisruption
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - service
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - service/status
  verbs:
  - get
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulehpainvalidscaletargetref
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulehpareplicapercentage
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - clusterrulesecretunused
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - notifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - notifiers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulehpareplicapercentage
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - secrets/status
  verbs:
  - get
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/status
  verbs:
  - get
