
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoscalingv1
  resources:
  - hpa
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - corev1
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - merlin.mercari.com
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - namespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - merlin.mercari.com
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
