# permissions to do edit rulehpareplicapercentage.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rulehpareachedmaxreplica-editor-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulehpareplicapercentage
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulehpareplicapercentage/status
  verbs:
  - get
  - patch
  - update
