# permissions to do edit rulepodresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rulepodresources-editor-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulepodresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulepodresources/status
  verbs:
  - get
  - patch
  - update
