# permissions to do edit rulepdbminalloweddisruptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rulepdbminalloweddisruption-editor-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulepdbminalloweddisruptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulepdbminalloweddisruptions/status
  verbs:
  - get
  - patch
  - update
