# permissions to do viewer rulepodresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rulepodresources-viewer-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulepodresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulepodresources/status
  verbs:
  - get
