# permissions to do viewer rulehpareplicapercentage.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rulehpareachedmaxreplica-viewer-role
rules:
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulehpareplicapercentage
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - merlin.mercari.com
  resources:
  - rulehpareplicapercentage/status
  verbs:
  - get
