apiVersion: merlin.mercari.com/v1
kind: ClusterRuleHPAReplicaPercentage
metadata:
  name: 90-percent
spec:
  ignoreNamespaces: # ignoreNamespaces is only for cluster rule
    - istio-system
    - kube-system
  percent: 90
  notification:
    notifiers:
      - slack-test
    suppressed: false
    severity: warning

