apiVersion: merlin.mercari.com/v1
kind: ClusterRulePDBInvalidSelector
metadata:
  name: cluster-rule-pdb-invalid-selector
spec:
  ignoreNamespaces:
    - istio-system
    - kube-system
    - test
  notification:
    notifiers:
      - slack-test
    suppressed: false
    severity: info
