apiVersion: merlin.mercari.com/v1
kind: ClusterRuleHPAReplicaPercentage
metadata:
  name: cluster-rule-hpa-replica-percentage-90
spec:
  ignoreNamespaces: # ignoreNamespaces is only for cluster rule
    - istio-system
    - kube-system
  percent: 90
  notification:
    notifiers:
      - slack-test
    suppressed: false
    severity: warning

---
apiVersion: merlin.mercari.com/v1
kind: ClusterRuleHPAReplicaPercentage
metadata:
  name: cluster-rule-hpa-replica-percentage-80
spec:
  ignoreNamespaces:
    - istio-system
    - kube-system
  percent: 80
  notification:
    notifiers:
      - slack-test
    suppressed: false
    severity: warning
