apiVersion: merlin.mercari.com/v1beta1
kind: ClusterRuleHPAInvalidScaleTargetRef
metadata:
  name: invalid-scale-target-ref
spec:
  ignoreNamespaces: # ignoreNamespaces is only for cluster rule
    - istio-system
    - kube-system
  notification:
    notifiers:
      - slack-test
    suppressed: false
    severity: warning
