apiVersion: merlin.mercari.com/v1beta1
kind: RuleHPAReplicaPercentage
metadata:
  namespace: default
  name: 100-percent
spec:
  selector: # selector is only for namespaced rule
    name: nginx
    matchLabels:
      app: nginx
  percent: 100
  notification:
    notifiers:
      - slack-test
    suppressed: false
    customMessageTemplate: "[{{.Severity}}] [`{{.ResourceName}}`] HPA current replica number percentage is 100%"
    severity: warning

