apiVersion: merlin.mercari.com/v1
kind: Notifier
metadata:
  name: slack-test
spec:
  slack:
    severity: "warning" # every channel has its default severity, but can be override by the rule
    channel: "your_channel"
    webhookURL: "your_webhook_url"

