apiVersion: watcher.merlin.mercari.com/v1
kind: NamespaceEvaluator
metadata:
  name: namespace-evaluator
spec:
  # Add fields here
  ignoreNamespaces:
    - kube-system
    - isto-system
    - test
    - spinnaker
    - cert-manager
    - prometheus
  istioInjection:
    label: "exists"
