apiVersion: watcher.merlin.mercari.com/v1
kind: DeploymentEvaluator
metadata:
  name: deployment-evaluator
spec:
  # Add fields here
  rules:
    canary:
      description: ""
      enabled: true
    replica:
      description: ""
      min: 3
      enabled: true
  ignoreNamespaces:
    - kube-system
    - isto-system
    - test
    - spinnaker
    - cert-manager
    - prometheus
