apiVersion: watcher.merlin.mercari.com/v1
kind: HPAEvaluator
metadata:
  name: hpa-evaluator
spec:
  ignoreNamespaces:
    - kube-system
    - isto-system
    - test
    - spinnaker
    - cert-manager
    - prometheus
  rules:
    reachedMaxReplica:
      enabled: true
    invalidMetrics:
      enabled: true


