# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/merlin.mercari.com_rulehpareplicapercentages.yaml
- bases/merlin.mercari.com_rulepodresources.yaml
- bases/merlin.mercari.com_notifiers.yaml
- bases/merlin.mercari.com_clusterrulehpareplicapercentages.yaml
- bases/merlin.mercari.com_clusterrulehpainvalidscaletargetrefs.yaml
- bases/merlin.mercari.com_clusterrulenamespacerequiredlabels.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_rulehpareplicapercentage.yaml
#- patches/webhook_in_rulepodresources.yaml
#- patches/webhook_in_notifier.yaml
#- patches/webhook_in_clusterrulehpareplicapercentages.yaml
#- patches/webhook_in_clusterrulehpainvalidscaletargetrefs.yaml
#- patches/webhook_in_clusterrulenamespacerequiredlabels.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_rulehpareplicapercentage.yaml
#- patches/cainjection_in_rulepodresources.yaml
#- patches/cainjection_in_notifier.yaml
#- patches/cainjection_in_clusterrulehpareplicapercentages.yaml
#- patches/cainjection_in_clusterrulehpainvalidscaletargetrefs.yaml
#- patches/cainjection_in_clusterrulenamespacerequiredlabels.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
