name: Build Docker Image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Output version
        id: version
        run: |
          echo ::set-output name=version::${GITHUB_REF##*/}

      - name: Build and push image
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:${{ steps.version.outputs.version }}

      - name: Build and push image for tags with latest
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.version.outputs.version }}
