name: Run Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install KubeBuilder
        run: |
          # From: https://kubebuilder.io/quick-start.html
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -sL https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
          mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin

      - name: Test
        run: make test

